# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csample_num <- function(x, size, replace) {
    .Call(`_support_csample_num`, x, size, replace)
}

energycrit <- function(Rcpp_point, Rcpp_des, cn, num_proc) {
    .Call(`_support_energycrit`, Rcpp_point, Rcpp_des, cn, num_proc)
}

starL2cpp <- function(D, cn, num_proc) {
    .Call(`_support_starL2cpp`, D, cn, num_proc)
}

energy_norm_cpp <- function(yMat, cn, num_proc) {
    .Call(`_support_energy_norm_cpp`, yMat, cn, num_proc)
}

obj_qsp <- function(des, distsamp, q) {
    .Call(`_support_obj_qsp`, des, distsamp, q)
}

grad_qsp <- function(des, distsamp, q) {
    .Call(`_support_grad_qsp`, des, distsamp, q)
}

thincpp <- function(Rcpp_point, Rcpp_inides, num_subsamp, bound, it_max, inn_it_max, innertol, outertol, epsilon, rate, num_proc) {
    .Call(`_support_thincpp`, Rcpp_point, Rcpp_inides, num_subsamp, bound, it_max, inn_it_max, innertol, outertol, epsilon, rate, num_proc)
}

sp_cpp <- function(des_num, dim_num, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, tol, num_proc) {
    .Call(`_support_sp_cpp`, des_num, dim_num, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, tol, num_proc)
}

