# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csample_num <- function(x, size, replace) {
    .Call(`_support_csample_num`, x, size, replace)
}

energycrit <- function(Rcpp_point, Rcpp_des, cn, num_proc) {
    .Call(`_support_energycrit`, Rcpp_point, Rcpp_des, cn, num_proc)
}

starL2cpp <- function(D, cn, num_proc) {
    .Call(`_support_starL2cpp`, D, cn, num_proc)
}

energy_norm_cpp <- function(yMat, cn, num_proc) {
    .Call(`_support_energy_norm_cpp`, yMat, cn, num_proc)
}

obj_qsp <- function(des, distsamp, q) {
    .Call(`_support_obj_qsp`, des, distsamp, q)
}

grad_qsp <- function(des, distsamp, q) {
    .Call(`_support_grad_qsp`, des, distsamp, q)
}

sp_cpp <- function(des_num, dim_num, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, it_min, tol, num_proc) {
    .Call(`_support_sp_cpp`, des_num, dim_num, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, it_min, tol, num_proc)
}

sp_seq_cpp <- function(cur, nseq, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, tol, num_proc) {
    .Call(`_support_sp_seq_cpp`, cur, nseq, ini, distind, distparam, distsamp, thin, bd, point_num, it_max, tol, num_proc)
}

gamma_eval <- function(dd, theta) {
    .Call(`_support_gamma_eval`, dd, theta)
}

omega <- function(theta_vec, gamma_vec, max_ord) {
    .Call(`_support_omega`, theta_vec, gamma_vec, max_ord)
}

opt_hess <- function(zz, omega_vec) {
    .Call(`_support_opt_hess`, zz, omega_vec)
}

psp_mi <- function(xx, omega_mat, samp_mat, des_mat, des_num, ii) {
    .Call(`_support_psp_mi`, xx, omega_mat, samp_mat, des_mat, des_num, ii)
}

psp_cpp <- function(Rcpp_inides, distind, distparam, gam_param, gamma_vec, max_ord, distsamp, thinind, gamsamp, gamind, bd, point_num, gam_point_num, it_max, tol, num_proc) {
    .Call(`_support_psp_cpp`, Rcpp_inides, distind, distparam, gam_param, gamma_vec, max_ord, distsamp, thinind, gamsamp, gamind, bd, point_num, gam_point_num, it_max, tol, num_proc)
}

psp_seq_cpp <- function(cur, nseq, ini, distind, distparam, gam_param, gamma_vec, max_ord, distsamp, thin, gamsamp, gamind, bd, point_num, gam_point_num, it_max, tol, num_proc) {
    .Call(`_support_psp_seq_cpp`, cur, nseq, ini, distind, distparam, gam_param, gamma_vec, max_ord, distsamp, thin, gamsamp, gamind, bd, point_num, gam_point_num, it_max, tol, num_proc)
}

